services:
    app.cas_authenticator:
        class: AlexandreT\CasGuardBundle\Security\CasAuthenticator
        autowire: false
        arguments:
            - '@doctrine.orm.default'
            - '@security.token_storage'
            - '@router'
            - '%cas%'