services:
    phpcasguard.cas_service:
        arguments:
           - '%cas_config%'
    phpcasguard.cas_authenticator:
        class: AlexandreT\Bundle\CasGuardBundle\Security\CasAuthenticator
        autowire: false
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.token_storage'
            - '@router'
            - '@phpcasguard.cas_service'
