services:
    cas_authenticator:
        class: AlexandreT\Bundle\CasGuardBundle\Security\CasAuthenticator
        autowire: false
        arguments:
            - '@doctrine.orm.default'
            - '@security.token_storage'
            - '@router'
            - '%cas%'