# Project language
language: php

php:
  # aliased to a recent 5.6.x version
  - 5.6
  # aliased to a recent 7.x version
  - 7.0
  # aliased to a recent 7.x version
  - 7.1
  # aliased to a recent 7.x version
  - 7.2
  # aliased to a recent hhvm version
  - hhvm

# Matrix to test in every php version
matrix:
  # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
  fast_finish: true
  allow_failures:
    - php: hhvm

# Define an environment variable
env:
  - SYMFONY_VERSION="2.8.*"
  - SYMFONY_VERSION="3.0.*"
  - SYMFONY_VERSION="3.1.*"
  - SYMFONY_VERSION="3.2.*"
  - SYMFONY_VERSION="3.3.*"
  - SYMFONY_VERSION="3.4.*"

# Update composer
before-install:
  - composer self-update

before_script:
  - composer install

script:
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then travis_wait 40 php vendor/phpunit/phpunit/phpunit --coverage-clover build/logs/clover.xml; fi
  - if [ "$TRAVIS_PHP_VERSION" != "5.6" ]; then php vendor/phpunit/phpunit/phpunit ; fi

after_success:
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then composer require satooshi/php-coveralls --no-interaction --prefer-source; fi
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then php vendor/bin/coveralls -v; fi

notifications:
  email:
    - alexandre.tranchant@gmail.com
