language: php

# Allows using containers
sudo: false

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache

# Base versions to test raw with the Symfony latest version.
php:
  - 7.1
  - 7.2
  - hhvm

# The Symfony version implies that you require the full framework, not single components
# Requiring single components is much harder to do... And probably not flexible enough, even if it's lighter.
env:
  global:
    - SYMFONY_VERSION=""

# Heavy matrix to test every version of the bundle/package
matrix:
  # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
  fast_finish: true
  include:
    # Lowest dependency
    - php: 7.1
      env: SYMFONY_VERSION="3.4.x"
    - php: 7.2
      env: SYMFONY_VERSION="3.4.x"
    - php: 7.1
      env: SYMFONY_VERSION="4.0.x"
    - php: 7.2
      env: SYMFONY_VERSION="4.0.x"
    - php: 7.1
      env: SYMFONY_VERSION="4.1.x"
    - php: 7.2
      env: SYMFONY_VERSION="4.1.x"
    - php: 7.1
      env: SYMFONY_VERSION="4.2.x"
    - php: 7.2
      env: SYMFONY_VERSION="4.2.x"
    - php: 7.1
      env: SYMFONY_VERSION="4.3.x"
    - php: 7.2
      env: SYMFONY_VERSION="4.3.x"
  allow_failures:
    - php: hhvm
    - env: SYMFONY_VERSION="4.3.x"

# Update composer, and update Symfony version depending on the matrix
before_install:
  - composer selfupdate
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony:$SYMFONY_VERSION; fi
  - mkdir -p build/logs

# Install composer dependencies,
#  but also phpunit (to test a specific version of it)
#  and coveralls (to send the code coverage to coveralls.io, see "after_success" later in this file)
# Note: for coveralls to work you need a ".coveralls.yml" file (see other file in this gist).
install:
  - composer install
#  - composer require --dev phpunit/phpunit:~5.0
  - composer require --dev satooshi/php-coveralls:~2.0

# Run script and log coverage in the "build" directory
script:
  - vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml

# Run coveralls after success and if not in hhvm (too much cache, incorrect coverage)
after_success: |
  if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v ; fi;
# After a build, sends a notification to this e-mail with the build results.
notifications:
  email: alexandre.tranchant@gmail.com
